[theme]
primaryColor = "#4CAF50"
backgroundColor = "#f5f7f9"
secondaryBackgroundColor = "#e2f0fd"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200

[runner]
magicEnabled = true
fastReruns = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true

[global]
developmentMode = false
logLevel = "info" 